(function () {
  'use strict';
  var storage = window.RealtorStorage; storage.seed();
  var page = document.body.getAttribute('data-page') || 'dashboard';
  var properties = window.RealtorProperties.all(); var rentals = window.RealtorRentals.all();
  function renderDashboard() { var available = properties.filter(function (p) { return p.status === 'disponible'; }).length; var rented = properties.filter(function (p) { return p.status === 'rentada'; }).length; var content = '<header class="topbar"><div><p class="eyebrow">Visão geral</p><h1>Bom dia, gestor.</h1><p class="muted">Acompanhe o que está acontecendo com seus imóveis.</p></div><a class="button" href="pages/add-property.html">+ Novo imóvel</a></header><div id="flash"></div><section class="metrics"><div class="metric"><span class="metric-label">Total de imóveis</span><strong class="metric-value">' + properties.length + '</strong><span class="metric-note">Carteira completa</span></div><div class="metric"><span class="metric-label">Disponíveis</span><strong class="metric-value">' + available + '</strong><span class="metric-note">Prontos para alugar</span></div><div class="metric"><span class="metric-label">Alugados</span><strong class="metric-value">' + rented + '</strong><span class="metric-note">Contratos ativos</span></div><div class="metric"><span class="metric-label">Receita mensal</span><strong class="metric-value">R$ ' + rentals.reduce(function (sum, item) { return sum + item.rentAmount; }, 0).toLocaleString('pt-BR') + '</strong><span class="metric-note">Contratos ativos</span></div></section><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Imóveis recentes</h2><a class="button button--quiet" href="pages/properties.html">Ver todos</a></div><div class="property-grid">' + properties.slice(0, 3).map(window.RealtorUI.card).join('') + '</div></section><section class="panel"><h2>Atividade recente</h2><ul class="activity"><li><i class="activity-dot"></i><div><strong>Carteira inicial criada</strong><span>6 imóveis adicionados ao sistema</span></div></li><li><i class="activity-dot"></i><div><strong>Contratos ativos</strong><span>' + rentals.length + ' locações em acompanhamento</span></div></li><li><i class="activity-dot"></i><div><strong>Próxima ação</strong><span>Revise os imóveis disponíveis</span></div></li></ul></section></div>'; document.getElementById('app').innerHTML = window.RealtorUI.shell('dashboard', content); var flash = storage.takeFlash(); if (flash) document.getElementById('flash').innerHTML = '<div class="flash">' + flash.message + '</div>'; }
  function renderProperties() { var cards = properties.map(window.RealtorUI.card).join(''); document.getElementById('app').innerHTML = window.RealtorUI.shell('properties', '<header class="topbar"><div><p class="eyebrow">Carteira</p><h1>Meus imóveis</h1><p class="muted">' + properties.length + ' imóveis registrados.</p></div><a class="button" href="add-property.html">+ Novo imóvel</a></header><section class="property-grid">' + cards + '</section>'); }
  function renderPlaceholder(title, active, subtitle) { document.getElementById('app').innerHTML = window.RealtorUI.shell(active, '<header class="topbar"><div><p class="eyebrow">Realtor</p><h1>' + title + '</h1><p class="muted">' + subtitle + '</p></div></header><section class="form-card"><p class="muted">Esta área está pronta para receber o próximo fluxo da aplicação.</p></section>'); }
  if (page === 'dashboard') renderDashboard(); else if (page === 'properties') renderProperties(); else if (page === 'add-property') renderPlaceholder('Novo imóvel', 'add-property', 'Cadastre uma propriedade na sua carteira.'); else if (page === 'rent-property') renderPlaceholder('Registrar locação', 'rent-property', 'Associe um imóvel a um inquilino.'); else renderPlaceholder('Realtor', 'dashboard', 'Gestão de renda de propriedades.');
}());