(function () {
  'use strict';
  var icons = { grid: '<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><rect x="14" y="14" width="6" height="6"/></svg>', home: '<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-6h6v6"/></svg>', plus: '<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>', key: '<svg viewBox="0 0 24 24"><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8m-3 3 2 2"/></svg>', users: '<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20c.4-3.5 2.4-5 6-5s5.6 1.5 6 5M16 5c2.2.3 3.5 1.7 3.5 4S18.2 12.7 16 13"/></svg>', edit: '<svg viewBox="0 0 24 24"><path d="m4 16-.7 4.7L8 20l11-11-4-4zM13.5 6.5l4 4"/></svg>' };
  var links = [{ key: 'dashboard', label: 'Dashboard', href: '../index.html', icon: 'grid' }, { key: 'properties', label: 'Meus imóveis', href: 'pages/properties.html', icon: 'home' }, { key: 'tenants', label: 'Inquilinos', href: 'pages/tenants.html', icon: 'users' }, { key: 'add-property', label: 'Novo imóvel', href: 'pages/add-property.html', icon: 'plus' }, { key: 'rent-property', label: 'Registrar locação', href: 'pages/rent-property.html', icon: 'key' }];
  function shell(activeKey, content) { var inPages = activeKey !== 'dashboard'; var nav = links.map(function (link) { var href = link.key === 'dashboard' ? (inPages ? '../index.html' : 'index.html') : (inPages ? link.href.replace('pages/', '') : link.href); return '<a class="' + (link.key === activeKey ? 'is-active' : '') + '" href="' + href + '">' + icons[link.icon] + '<span>' + link.label + '</span></a>'; }).join(''); var brandHref = inPages ? '../index.html' : 'index.html'; return '<div class="shell"><aside class="sidebar"><a class="brand" href="' + brandHref + '"><span class="brand-mark">R</span><span><strong>Realtor</strong><small>gestão simples</small></span></a><nav class="nav" aria-label="Navegação principal">' + nav + '</nav></aside><section class="content">' + content + '</section></div>'; }
  function statusLabel(status) { return { disponible: 'Disponível', rentada: 'Alugada', 'en mantenimiento': 'Manutenção' }[status] || status; }
  function badge(status) { var kind = { disponible: 'available', rentada: 'rented', 'en mantenimiento': 'maintenance' }[status] || 'available'; return '<span class="badge badge--' + kind + '">' + statusLabel(status) + '</span>'; }
  function card(property) { return '<article class="property-card"><img src="' + property.image + '" alt="Imagem de ' + property.title + '" onerror="this.onerror=null;this.src=\'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22800%22 height=%22500%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%23dfe9e2%22/%3E%3C/svg%3E\'"><div class="property-card__body"><h3>' + property.title + '</h3><p class="property-card__address">' + property.address + '</p><p class="property-card__description">' + (property.description || 'Sem descrição informada.') + '</p><div class="property-card__details"><span>' + property.bedrooms + ' quartos</span><span>' + property.bathrooms + ' banheiros</span></div><div class="property-card__meta">' + badge(property.status) + '<strong>R$ ' + property.price.toLocaleString('pt-BR') + '</strong></div><a class="button button--quiet property-card__action" href="edit-property.html?id=' + property.id + '">' + icons.edit + ' Editar</a></div></article>'; }
  function renderTenantRow(tenant) { return '<article class="tenant-row"><div><h3>' + tenant.name + '</h3><p>' + tenant.email + '</p><p>' + tenant.phone + ' · Documento: ' + tenant.documentId + '</p>' + (tenant.notes ? '<p class="tenant-row__notes">' + tenant.notes + '</p>' : '') + '</div><a class="button button--quiet" href="edit-tenant.html?id=' + tenant.id + '">' + icons.edit + ' Editar</a></article>'; }
  function flash(message, type) { return '<div class="flash flash--' + (type || 'success') + '" role="status">' + message + '</div>'; }
  function confirmAction(message) { return window.confirm(message || 'Confirma esta ação?'); }
  window.RealtorUI = { shell: shell, statusLabel: statusLabel, badge: badge, card: card, renderTenantRow: renderTenantRow, flash: flash, confirmAction: confirmAction, icons: icons };
}());
